### ISSUE TITLE
Inline disconnect button for chromecast/DLNA

### ISSUE THREAD

**Issue by ritz078** [ritz078/moose#238]
Right now if we want to disconnect an already connected chromecast, you have to toggle from the dropdown. It will be a better UX if we give a disconnect button in the right side of text.

<img width="903" alt="Screenshot 2021-01-31 at 3 15 30 PM" src="https://user-images.githubusercontent.com/5389035/106380292-46179080-63d7-11eb-97d3-42b8a37e424f.png">

**Comment by vinodf2f** [comment]
@ritz078 I would like to work on this issue. Can you assign it to me ?

**Comment by ritz078** [comment]
> I would like to work on this issue. Can you assign it to me ?

Done.

**Comment by vinodf2f** [comment]
@ritz078 Can we add a disconnect button like this ?

![Screenshot 2021-02-02 at 6 10 36 PM](https://user-images.githubusercontent.com/41716058/106601691-f628fd00-6581-11eb-9628-b3b429e5e255.png)

**Comment by ritz078** [comment]
The first one looks better. Can you change the color of the text to make it look like a link and underline on hover.

**Comment by vinodf2f** [comment]
Sure.

**Comment by vinodf2f** [comment]
Hi @ritz078, can you please review [this](https://github.com/ritz078/moose/pull/252) PR ?


Thanks.
