### ISSUE TITLE
Fresh install, already loading 5 torrents

### ISSUE THREAD

**Issue by mg** [ritz078/moose#73]
Hi

Intstalled the app and opened it, and the app was already downloading those 5 torrents in the screenshot in the Readme.

**Comment by ritz078** [comment]
As samples, I am loading 5 torrents at the start and now I understand how it's a bad idea. I will decrease it to 2 and give a simple way to get rid of all of that at once. Thanks for the feedback.

**Comment by nurkhz** [comment]
I don't even think 2 is a good idea, I have checked and I do not even know why do I need to download them. Next to that, some people (Like me) do not wanna use it without VPN and when you open the app if it starts to download right away, technically it may create some issues in some countries where the torrent is a big problem.
