### ISSUE TITLE
bag with player music 

### ISSUE THREAD

**Issue by cryptninja** [ritz078/moose#75]
buttons to stop playing and sound don`t work,  after playing one track there is no transition to the next
<img width="532" alt="Screen Shot 2020-06-15 at 12 46 36 AM" src="https://user-images.githubusercontent.com/40059218/84599041-b5209300-aea1-11ea-82c6-bc98b5521b87.png">

**Comment by ritz078** [comment]
This has been fixed in the latest release and the app should auto update.
