### ISSUE TITLE
How to update app on Mac 

### ISSUE THREAD

**Issue by numbchicken** [ritz078/moose#96]
Hi im a new user of this app and was wondering what the process is for updating the app with the latest patches that are released on my macbook? Do I just download and run the .dmg file of the updated moose app or do I also download the .zip folder that is also available in the assets section of, for example the latest update 0.6.2, to update my moose app to version 0.6.2 do I just download the .dmg file in the assets section or do I also download and run the zip file thats also there and the moose-0.6.2.dmg.blockmap file thats sthere too?

**Comment by ritz078** [comment]
If you have installed one of the recent versions, the auto updates itself in background when you are using the app. If that isn't working, you should use the `.dmg`
